// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nqygotcdtvfokmgukpnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeWdvdGNkdHZmb2ttZ3VrcG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzQxMzEsImV4cCI6MjA3OTE1MDEzMX0.48PzA7eLoRz3JXvywAKWx87ubHKEHLFLhQDYfWSYMls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);